language: python
python:
- '3.4'
cache: pip
install:
- pip3 install https://github.com/jnewland/home-assistant/zipball/rancho-de-newland
script:
- openssl req -x509 -newkey rsa:1024 -subj '/CN=example.com' -nodes -keyout /tmp/key.pem -out /tmp/cert.pem
- hass -c . --script check_config -i all -f | tee /tmp/log
- test "$(grep -c ERROR /tmp/log)" -eq 0
env:
- ALARM_PASSWORD=""
  ALARM_PLATFORM=alarmdotcom
  ALARM_USERNAME=""
  API_PASSWORD=""
  APPLETV_LOGIN_ID=""
  BEDROOM_APPLE_TV_IP=""
  BEDROOM_TV_IP=""
  BEDROOM_TV_MAC=""
  CAMERA_DASH=http://example.com
  CAMERA_URL_1=http://example.com
  CAMERA_URL_2=http://example.com
  CAMERA_URL_3=http://example.com
  CAMERA_URL_4=http://example.com
  CAMERA_URL_5=http://example.com
  CAMERA_URL_6=http://example.com
  CAMERA_URL_7=http://example.com
  CAMERA_URL_8=http://example.com
  CAMERA_URL_9=http://example.com
  CLIMATE_DASH=http://example.com
  DESK_HID_IDLE_TIME_RESOURCE=http://example.com
  ELEVATION=0
  FORECAST_API_KEY=""
  GATEWAY_LINK=http://example.com
  GRAFANA_LINK=http://example.com
  GRAPHITE_LINK=http://example.com
  HUE_IP=""
  IFTTT_KEY=""
  ITUNES_IP=""
  ITUNES_URL=""
  JESSE_MUSIC_ROOM_IP="0.0.0.0"
  JPHONE_PUSH_TARGET=""
  KITCHEN_LAT=0
  KITCHEN_LONG=0
  LAT=0
  LETSENCRYPT_EMAIL=""
  LETSENCRYPT_HOST=""
  LONG=0
  MASTER_LAT=0
  MASTER_LONG=0
  MOTION_LINK=http://example.com
  MPR_API_IP=""
  MPR_API_PORT=1
  MYQ_PASSWORD=""
  MYQ_USERNAME=""
  NUC_IP=""
  OFFICE_APPLE_TV_IP=""
  OFFICE_LAT=0
  OFFICE_LONG=0
  OFFICE_TV_IP=""
  OFFICE_TV_MAC=""
  ROUTER_LINK=http://example.com
  SELF_LINK=http://example.com
  SLACK_API_KEY=""
  SMOKEPING_LINK=http://example.com
  SSL_CERTIFICATE=/tmp/cert.pem
  SSL_KEY=/tmp/key.pem
  TRUSTED_NETWORK_1=0.0.0.0/0
  TRUSTED_NETWORK_2=0.0.0.0/0
  TRUSTED_NETWORK_3=0.0.0.0/0
  UNIFI_USERNAME=foo
  UNIFI_PASSWORD=bar
  UNIFI_PORT=8443
  VERA_LINK=http://example.com
  VERA_URL=http://example.com
  VIRTUAL_HOST=example.com
  VIRTUAL_NETWORK=""
  VIRTUAL_PORT=""
notifications:
  email: false
  slack:
    secure: DdLNc+RIgx8lYa+H08Fg3eY6C6Dg99lhORe3uJbdVGy8M39ctEQnMfhg/P5yIiXKqCzzvdpTCpbt486U5goVC6gNY0qN7Q/9DIi9QZU/UlK7XtiPUslJOQdzy7ecavntzc3e1vhvkbhdp7RkJEyMiwcNePzj6eKho1BnczL1g7Dn21F4kUOCEXuIFXNHN6lLI8uCvso0n7gGxb2HU+aYROuAImgqUv9esbJUWo7L+b5YG4tIXPqrykA6Bz1/iYCng6OWmm9+BpSRrmiGcVf3d0OfDT9OwYnNpGhG6pGYMQmtACNAPsrOnraNBa6DarxKfqNpgkiOfefqGcVI9WVO1opcABOVxnSNbZZqx08Og2Gon9rpLQodE0NoMVrIENiBD+lGyu4Fdagckz3asy3WNPEUlu+Qm0qMuxablHrxJc3DEjMIi6UKmKOkgIszH/T5WFKSd4+jLBPej4xG/8F+0S1aP5BTEMMS+gbBabmCoHmZivxU6uknIuID64TNTZLmKV4x8VQJKUtDfW7O8KKLXUKlwN/C0tlNF5XtphxNprIzGNrADplJmULvpDkqo7X4G25VHi3dWh+tn2r+k4kcJOK3WbOfDFzSKouwTJSMaiWyUl/GWbQWweyFTQOw8MPjMNhff3AtM+AQbe5TPTDpB/b3yf48X4ui9mttzl63AIo=
