language: python
python:
- "3.4"
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config | tee /tmp/log
- test "$(grep -c ERROR /tmp/log)" -eq 0
env:
  - ALARM_PASSWORD="" ALARM_PLATFORM="" ALARM_USERNAME="" API_PASSWORD="" APPLETV_LOGIN_ID="" BEDROOM_APPLE_TV_IP="" BEDROOM_TV_IP="" BEDROOM_TV_MAC="" CAMERA_DASH="" CAMERA_URL_1="" CAMERA_URL_2="" CAMERA_URL_3="" CAMERA_URL_4="" CAMERA_URL_5="" CAMERA_URL_6="" CAMERA_URL_7="" CAMERA_URL_8="" CAMERA_URL_9="" CLIMATE_DASH="" DESK_HID_IDLE_TIME_RESOURCE="" ELEVATION="" FORECAST_API_KEY="" GATEWAY_LINK="" GRAFANA_LINK="" GRAPHITE_LINK="" HUE_IP="" IFTTT_KEY="" ITUNES_IP="" ITUNES_URL="" JPHONE_PUSH_TARGET="" KITCHEN_LAT="" KITCHEN_LONG="" LAT="" LETSENCRYPT_EMAIL="" LETSENCRYPT_HOST="" LONG="" MASTER_LAT="" MASTER_LONG="" MOTION_LINK="" MPR_API_IP="" MPR_API_PORT="" MQTT_BROKER="" MQTT_PASSWORD="" MQTT_PORT="" MQTT_USERNAME="" MYQ_PASSWORD="" MYQ_USERNAME="" NUC_IP="" OFFICE_APPLE_TV_IP="" OFFICE_LAT="" OFFICE_LONG="" OFFICE_TV_IP="" OFFICE_TV_MAC="" ROUTER_LINK="" SELF_LINK="" SLACK_API_KEY="" SMOKEPING_LINK="" SSL_CERTIFICATE="" SSL_KEY="" TRUSTED_NETWORK_1="" TRUSTED_NETWORK_2="" TRUSTED_NETWORK_3="" VERA_LINK="" VERA_URL="" VIRTUAL_HOST="" VIRTUAL_NETWORK="" VIRTUAL_PORT=""
