- platform: rest
  resource: !env_var DESK_HID_IDLE_TIME_RESOURCE
  name: Jesse's desktop
  value_template: '{{ value_json < 60}}'
- platform: template
  sensors:
    rain_today:
      entity_id:
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      value_template: |
        {{
          states.sensor.dark_sky_daily_max_precip_intensity.state != None and
          states.sensor.dark_sky_precip_probability.state != None and
          states.sensor.dark_sky_precip_intensity.state != None and
          (
            float(states.sensor.dark_sky_daily_max_precip_intensity.state) > 0 or
            float(states.sensor.dark_sky_precip_probability.state) > 0 or
            float(states.sensor.dark_sky_precip_intensity.state) > 0
          )
        }}
    together:
      entity_id:
      - device_tracker.jphone_6s
      - device_tracker.katies_iphone
      value_template: |
        {{
          states.device_tracker.katies_iphone != None and
          states.device_tracker.jphone_6s != None and
          distance(states.device_tracker.jphone_6s, states.device_tracker.katies_iphone) != None and
          distance(states.device_tracker.jphone_6s, states.device_tracker.katies_iphone) < 0.25
        }}
