icon: mdi:rocket
control: hidden
entities:
- script.restart
- script.reload_core_config
- weblink.upstream_changes
- weblink.haconfig
- sensor.jnewlandhaconfig_branch
- sensor.jnewlandhomeassistant_branch
