control: hidden
name: Deployment
entities:
- weblink.ci
- weblink.haconfig
- sensor.haconfig_branch
- script.deploy_haconfig
- script.script.deploy_haconfig_master
- sensor.home_assistant_branch
- weblink.upstream_changes
- script.restart
