---
entities:
- sun.sun
- sensor.todays_uv_index
- sensor.todays_low_uv_hours
- sensor.dark_sky_apparent_temperature
- sensor.dark_sky_minutely_summary
- sensor.dark_sky_hourly_summary
- sensor.dark_sky_daily_summary
- camera.radar
