# Keep the gate closed
alias: Auto gate
trigger:
  platform: state
  entity_id: cover.gate
  to: open
  for:
    minutes: 1
condition:
  condition: template
  value_template: '{{ states.input_select.mode.state != "Pause" }}'
action:
- service: script.ask_about_turning_on
  data_template:
    entity_id: script.lock_up
    message: "The gate has been open for a bit. Close it up?"
    camera_entity_id: camera.gate
