# Keep the garage closed
alias: Auto garage
trigger:
  platform: state
  entity_id: cover.garage
  to: open
  for:
    minutes: 5
condition:
  condition: template
  value_template: '{{ states.input_select.mode.state != "Pause" }}'
action:
- service: script.ask_about_turning_on
  data_template:
    entity_id: script.lock_up
    message: "The garage has been open for a bit. Close it up?"
    camera_entity_id: camera.garage
