alias: Bathroom motion start
trigger:
  platform: state
  entity_id: binary_sensor.master_bath_motion_37
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.light.master_mirror_35.state == "off" and states.light.master_bath_overhead_36.state == "off" and states.light.master_shower_34.state == "off" }}'
    - condition: template
      value_template: '{{ states.input_select.mode.state != "Pause" }}'
action:
  service: script.turn_on
  entity_id: script.bathroom_motion_start
