alias: Show people on dashboard only if interesting
trigger:
  platform: state
  entity_id:
    - binary_sensor.together
    - sensor.haconfig_sha
action:
  service: script.group_visibility
  data:
    entity_id: group.people
    cond: binary_sensor.together
    visible_state: 'off'
