alias: Show people on dashboard only if interesting
trigger:
  platform: state
  entity_id: binary_sensor.together
action:
  service: script.group_visibility
  data:
    entity_id: group.activity
    cond: binary_sensor.together
    visible_state: 'off'
