alias: Activity on the iMac means Jesse is in the office
trigger:
  - platform: state
    entity_id: binary_sensor.jesses_desktop
    to: 'on'
  - platform: time
    seconds: '/10'
condition:
  condition: template
  value_template: |
    {{ states.binary_sensor.jesses_desktop.state == "on" }}
action:
  - service: device_tracker.see
    data_template:
      dev_id: jphone_6s
      location_name: Office
      gps:
      - !env_var OFFICE_LAT
      - !env_var OFFICE_LONG
