alias: Guest bath motion lights
trigger:
  platform: state
  entity_id: binary_sensor.guest_bath_motion_70
  from: 'off'
  to: 'on'
condition:
  condition: template
  value_template: |
    {{
      states.light.guest_bath_43.state == "off" and
      states.light.guest_shower_44.state == "off" and
      states.input_select.mode.state != "Pause"
    }}
action:
  service: light.turn_on
  entity_id:
    - light.guest_bath_43
    - light.guest_shower_44
