alias: Katie is home
trigger:
  platform: state
  entity_id: device_tracker.kphone_kphone
  from: not_home
  to: home
condition:
  condition: state
  entity_id: device_tracker.jphone_6s
  state: home
action:
  service: notify.slack
  data:
    message: '@jnewland Katie is home!'
    target: "#general"
