alias: Master bath motion lights
trigger:
  platform: state
  entity_id: binary_sensor.master_bath_motion_37
  from: 'off'
  to: 'on'
condition:
  condition: template
  value_template: |
    {{
      states.light.master_mirror_35.state == "off" and
      states.light.master_bath_overhead_36.state == "off" and
      states.light.master_shower_34.state == "off" and
      states.input_select.mode.state != "Pause"
    }}
action:
  service: scene.turn_on
  data_template:
    entity_id: |
      {% if states.input_select.mode.state == "Sleeping" %}
      scene.master_bathroom_nightlight
      {% else %}
      scene.master_bathroom_full_blast
      {% endif %}
