alias: Motion device
trigger:
  platform: state
  entity_id:
  - binary_sensor.stairs_motion_6
  - binary_sensor.closet_motion_61
  - binary_sensor.guest_bath_motion_70
  - binary_sensor.powder_room_motion_75
  - binary_sensor.office_motion_82
  - binary_sensor.upstairs_motion_87
  - binary_sensor.master_bath_motion_37
condition:
  condition: template
  value_template: '{{ states.input_select.mode.state != "Pause" }}'
action:
  service: device_tracker.see
  data_template:
    dev_id: motion
    location_name: >
      {%-
        if states.binary_sensor.stairs_motion_6.state == "off" and
           states.binary_sensor.closet_motion_61.state == "off" and
           states.binary_sensor.guest_bath_motion_70.state == "off" and
           states.binary_sensor.powder_room_motion_75.state == "off" and
           states.binary_sensor.office_motion_82.state == "off" and
           states.binary_sensor.upstairs_motion_87.state == "off"
      -%}
      not_home
      {%- elif trigger.to_state.state == "on" -%}
      {{- trigger.to_state.attributes.zone -}}
      {% endif %}
