alias: Motion device not home
trigger:
  platform: time
  seconds: '/30'
condition:
  condition: template
  value_template: |
    {{ as_timestamp(utcnow()) - as_timestamp(states.device_tracker.motion.last_changed) > 300 }}
action:
  service: device_tracker.see
  data_template:
    dev_id: motion
    location_name: not_home
