alias: Music room zone
trigger:
  platform: state
  entity_id: device_tracker.jesse_music_room
  to: 'home'
condition:
  condition: template
  value_template: |
    {{ states.input_select.mode.state != "Pause" }}
action:
  service: device_tracker.see
  data_template:
    dev_id: jphone_6s
    location_name: |
      {%- if trigger.to_state.state == "on" -%}
      Music room
      {%- else -%}
      Upstairs
      {%- endif -%}
