alias: notify when master ac is leaking
trigger:
  platform: state
  entity_id: binary_sensor.master_ac_water_13
  from: 'off'
  to: 'on'
action:
  service: notify.ios_jphone_6s
  data:
    message: 'the master AC water sensor detected a leak'
