alias: startup
trigger:
  platform: homeassistant
  event: start
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.mode
      option: Working
  - service: input_select.select_option
    data_template:
      entity_id: input_select.playlist
      option: Idle
