# If no one has been upstairs for an hour and it's above 74, set the thermostat
# to 78 to save some energy
alias: Upstairs auto climate
trigger:
  - platform: state
    entity_id: binary_sensor.motion_upstairs
    to: 'off'
    for:
      hours: 1
condition:
  condition: and
  conditions:
  - condition: template
    value_template: |
      {{
        states.climate.upstairs_28.attributes.current_temperature | default(72) > 74
      }}

  - condition: template
    value_template: |
      {{
        states.input_select.mode.state != "Pause" and
        states.input_select.mode.state != "Sleeping" and
        states.input_select.mode.state != "Reading"
      }}
action:
  - service: climate.set_operation_mode
  - service: climate.set_temperature
    data_template:
      entity_id: climate.upstairs_28
      temperature: 78
